version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: xawek/foodgram_backend
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: xawek/foodgram_frontend
    env_file: ../.env
    volumes:
      - static:/app/result_build

  nginx:
    image: nginx:1.19.3
    env_file: ../.env
    ports:
      - 9090:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/static/api/docs
      - static:/static
      - media:/media
    depends_on:
      - db

